Models/Sglookup.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Security.Cryptography.Pkcs;

namespace RoleBasedAuthorization.Models
{

    public partial class Sglookup
    {
        MyDbContext _db = new MyDbContext();
        [Key]
        public int LookupID { get; set; }

        public string Status { get; set; }

        public string BillingMonth { get; set; }
        public string JoinedDate { get; set; }
        public string PacteraEdgeEmail { get; set; }

        public string Contract { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string oneforma { get; set; }

        //public string UHRS { get; set; }

        public string PayRateUS { get; set; }

        public string UserID { get; set; }

        public int SumOfTimeActive { get; set; }

        public int SumOfTimeInactive { get; set; }

        public decimal TotalTime { get; set; }

        public decimal Hrs { get; set; }

        public decimal ActiveHrs { get; set; }

        public decimal InactiveHrs { get; set; }

        public decimal BillableInactiveHrs { get; set; }

        public decimal TotalHrs { get; set; }

        public decimal Productivity { get; set; }

        public decimal ProductivityPercentage { get; set; }

        public string deleted { get; set; }

        public string averagerating { get; set; }

        public decimal quality { get; set; }

        public decimal qualitypercentage { get; set; }

        public decimal averagescore { get; set; }

        public decimal finalamountpayable { get; set; }
        //public List<SelectListItem> Lookups { get; set; }

        //public decimal UHRSMonthDiscrepancy { get; set; }
        //public decimal UHRSAdditional { get; set; }
        //public decimal UHRSNonJA { get; set; }
        public decimal USDTotal { get; set; }

        public string dashboardstatus { get; set; }
        
        public string createdby { get; set; }
        public string comment { get; set; }
    }   

}

Controllers/SglookupController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RoleBasedAuthorization.Models;
using System;
using System.Linq;
using System.Threading.Tasks;
using ClosedXML.Excel;
using System.Data;

using System.Text;
using System.Collections.Generic;
using MySql.Data.MySqlClient;
using Microsoft.Extensions.Configuration;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace RoleBasedAuthorization.Controllers
{
    public class SglookupController : Controller
    {
        MyDbContext _context = new MyDbContext();
        public static IConfiguration Configuration;

        public SglookupController(IConfiguration _configuration)
        {
            Configuration = _configuration;
        }

        [AuthorizedAction]
        public async Task<IActionResult> Index(
       string sortOrder,
       string currentFilter,
       string searchString,
       int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;
            //var temp = from s in _context.sglookup
            //               select new { s.LookupID, s.FirstName, s.LastName, s.JoinedDate };
            int createdBy = HttpContext.Session.GetInt32("id").Value;
            //var inq = "Pending";
            var num = "false";
            var useremail = HttpContext.Session.GetString("email").ToString();
            
            IQueryable<Sglookup> students;
            if (createdBy.Equals(1))
            {
                students = from s in _context.Sglookup
                           where num.Contains(s.deleted)
                           select s;
            }
            else
            {
                students = from s in _context.Sglookup
                           where num.Contains(s.deleted) 
                           select s;

            }
            //select new { s.LookupID, s.FirstName, s.LastName, s.JoinedDate};
            if (!String.IsNullOrEmpty(searchString))
            {
                students = students.Where(s => s.BillingMonth.Contains(searchString)
                                       || s.PacteraEdgeEmail.Contains(searchString)
                                       || s.Contract.Contains(searchString)
                                       || s.PayRateUS.Contains(searchString)
                                       || s.Status.Contains(searchString)
                                       );
            }
            switch (sortOrder)
            {
                case "name_desc":
                    students = students.OrderByDescending(s => s.LookupID);
                    break;
                case "Date":
                    students = students.OrderBy(s => s.JoinedDate);
                    break;
                case "date_desc":
                    students = students.OrderByDescending(s => s.JoinedDate);
                    break;
                default:
                    students = students.OrderBy(s => s.PacteraEdgeEmail);
                    break;
            }
            int pageSize = 10;
            int roleId = (int)HttpContext.Session.GetInt32("role_id");

            var _role = _context.Roles.Where(s => s.Id == roleId).FirstOrDefault();
            if (_role.Title.Contains("Manager"))
            {
                ViewBag.RoleLevel = _role.Title;
            }
            //return View(await students.AsNoTracking().ToListAsync());

            return View(await PaginatedList<Sglookup>.CreateAsync(students.AsNoTracking(), pageNumber ?? 1, pageSize));
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }
                
                int roleId = (int)HttpContext.Session.GetInt32("role_id");

                var _role = _context.Roles.Where(s => s.Id == roleId).FirstOrDefault();
                if (_role.Title.Contains("Manager"))
                {
                    ViewBag.RoleLevel = _role.Title;
                }
                var student = await _context.Sglookup.FindAsync(id);

                if (student == null)
                {
                    return NotFound();
                }
                return View(student);
            }
            catch (Exception)
            {
                throw;
            }
        }
        public static decimal GetFinalPaymentAmount(string email, int lookupID)
        {
            decimal count = 0;
            try
            {
                MySqlConnection conn = null;

                string myConn = Configuration.GetConnectionString("myConn");
                conn = new MySqlConnection(myConn);
                conn.Open();
                MySqlCommand cmd = conn.CreateCommand();
                cmd.CommandText = "select TotalHrs*PayRateUS* (averagescore /100) from sglookup WHERE PacteraEdgeEmail='" + email + "' and LookupID=" + lookupID;

                count = Convert.ToDecimal(cmd.ExecuteScalar());

                return count;
            }
            catch (Exception ex)
            {
                return 0;
            }
        }
        /// POST: Admins/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("LookupID,FirstName,LastName,Contract,PacteraEdgeEmail,TotalHrs")] Sglookup admins)
        {
            var usdtotal = Request.Form["USDTotal"].ToString();
            if (!string.IsNullOrEmpty(usdtotal))
            {
                usdtotal = usdtotal;
            }
            else
            {
                usdtotal = "0";
            }
            if (id != admins.LookupID)
            {
                return NotFound();
            }
            decimal finalpaymentamount = GetFinalPaymentAmount(admins.PacteraEdgeEmail,id);
            
            Sglookup admin = await _context.Sglookup.Where(s => s.LookupID == admins.LookupID).FirstOrDefaultAsync();
            admin.FirstName = admins.FirstName;
            admin.LastName = admins.LastName;
            admin.Contract = admins.Contract;
            admin.PacteraEdgeEmail = admins.PacteraEdgeEmail;
            admin.TotalHrs = admins.TotalHrs;
            admin.USDTotal = Convert.ToDecimal(usdtotal);
            admin.finalamountpayable = finalpaymentamount;

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var admins = await _context.Sglookup
                .SingleOrDefaultAsync(m => m.LookupID == id);
            if (admins == null)
            {
                return NotFound();
            }

            return View(admins);
        }
        // POST: Admins/DeleteConfirmed/5
        [HttpPost, ActionName("DeleteConfirmed")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var admins = await _context.Sglookup.SingleOrDefaultAsync(m => m.LookupID == id);
            admins.deleted = "true";
            //_context.Offlinehours.Remove(admins);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
       
        [HttpPost]
        public FileResult ExportToCSV()
        {
            
            MyDbContext entities = new MyDbContext();
            List<object> lstStudents = (from Student in entities.Sglookup.ToList()
                                        select new[] { Student.Status.ToString(),
                                                        Student.BillingMonth.ToString(),
                                                        Student.JoinedDate.ToString(),
                                                        Student.PacteraEdgeEmail.ToString(),
                                                        Student.Contract.ToString(),
                                                        Student.FirstName.ToString(),
                                                        Student.LastName.ToString(),
                                                        Student.oneforma.ToString(),
                                                        //Student.UHRS.ToString(),
                                                        Student.PayRateUS.ToString(),
                                                        Student.UserID.ToString(),
                                                        Student.SumOfTimeActive.ToString(),
                                                        Student.SumOfTimeInactive.ToString(),
                                                        Student.TotalTime.ToString(),
                                                        Student.Hrs.ToString(),
                                                        Student.ActiveHrs.ToString(),
                                                        Student.InactiveHrs.ToString(),
                                                        Student.BillableInactiveHrs.ToString(),
                                                        Student.TotalHrs.ToString(),
                                                        Student.Productivity.ToString(),
                                                        Student.ProductivityPercentage.ToString(),

Views/Sglookup/Delete.cshtml
@model RoleBasedAuthorization.Models.Sglookup

@{
    ViewData["Title"] = "Delete Summary Final Amount ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        @ViewData["Title"]
    </h1>
</section>
<!-- Main content -->
<section class="content container-fluid">
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">
            <h3>Are you sure you want to delete this?</h3>
            <div>
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.LookupID)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.LookupID)
                    </dd>                   
                    <dt>
                        @Html.DisplayNameFor(model => model.FirstName)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.FirstName)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.LastName)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.LastName)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Contract)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Contract)
                    </dd>
                     <dt>
                        @Html.DisplayNameFor(model => model.PacteraEdgeEmail)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.PacteraEdgeEmail)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.TotalHrs)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.TotalHrs)
                    </dd>
                </dl>

                <form method="post" action="/Sglookup/DeleteConfirmed">
                    <input type="hidden" name="id" value="@Model.LookupID" />
                    <input type="submit" value="Delete" class="btn btn-default" />
                </form>
            </div>
        </div>
    </div>
</section>

Views/Sglookup/Edit.cshtml
@model RoleBasedAuthorization.Models.Sglookup

@{
    ViewData["Title"] = "Summary Final Amount Function";
    
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        @ViewData["Title"]
    </h1>
</section>
<!-- Main content -->
<section class="content container-fluid">
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Edit Summary Final Amount Info</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form method="post" asp-action="/Sglookup/Edit">
                    <input type="hidden" class="form-control" id="LookupID" name="LookupID" value="@Model.LookupID" >

                    <div class="box-body">
                        <div class="form-group">
                            <label for="FirstName">FirstName</label>
                            <input type="text" class="form-control" id="FirstName" name="FirstName" value="@Model.FirstName" placeholder="Enter FirstName">
                        </div>
                        <div class="form-group">
                            <label for="LastName">LastName</label>
                            <input type="text" class="form-control" id="LastName" name="LastName" value="@Model.LastName" placeholder="Enter LastName">
                        </div>
                        <div class="form-group">
                            <label for="Contract">Contract</label>
                            <input type="text" class="form-control" id="Contract" name="Contract" value="@Model.Contract" placeholder="Enter Contract">
                        </div>
                        <div class="form-group">
                            <label for="PacteraEdgeEmail">PacteraEdgeEmail</label>
                            <input type="text" class="form-control" id="PacteraEdgeEmail" name="PacteraEdgeEmail" value="@Model.PacteraEdgeEmail" placeholder="Enter PacteraEdgeEmail">
                        </div>
                        <div class="form-group">
                            <label for="TotalHrs">TotalHrs</label>
                            <input type="text" class="form-control" id="TotalHrs" name="TotalHrs" value="@Model.TotalHrs" placeholder="Enter TotalHrs">
                        </div>
                        <div class="form-group">
                            <label for="USDTotal">Additional Project Allowance</label>
                            <input type="text" class="form-control" id="USDTotal" name="USDTotal" value="@Model.USDTotal" placeholder="Enter Project Allowance">
                        </div>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
            <!-- /.box -->
            @section Scripts
    {
    <!-- Bootstrap -->
    <link href="https://code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css" rel="Stylesheet"
    type="text/css" />
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.7.2.min.js"></script>
    <script type="text/javascript" src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>

}
        </div>
    </div>
</section>

Views/Sglookup/Index.cshtml
@model RoleBasedAuthorization.PaginatedList<RoleBasedAuthorization.Models.Sglookup>

@{
    ViewData["Title"] = "Listing Function";
    
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<html>
<head>
<style>
table {
    display: block;
    overflow-x: auto;
    white-space: nowrap;  
}
</style>
</head>
<body>
    <br/><br/><br/>
    <div class="row" style="margin-left:30px">
            <div class="panel-primary">
                @using (Html.BeginForm("ExportToCSV", "Sglookup", FormMethod.Post))
                {
                    <button type="submit" class="btn btn-success">
                        <i class="glyphicon glyphicon glyphicon-download"></i> Download CSV
                    </button>
                }
            </div>
        </div>
    <form asp-action="Index" method="get">
        
        <br/>
        
        <br/>
    <div class="form-actions no-color">
        <p>
            Find by data: <input type="text" name="SearchString" value="@ViewData["CurrentFilter"]" />
            <input type="submit" value="Search" class="btn btn-default" /> |
            <a asp-action="Index">Back to Full List</a>
        </p>
    </div>
    </form>
    <table id="example" class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellspacing="0">    
        <br/>
        <thead>
        <tr>
              <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">ID</a>
            </th>               
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">BillingMonth</a>

            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Joined Date</a>
                
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Contract</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Full Name</a>
            </th>
              <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">PacteraEdgeEmail</a>
            </th>      
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">PayRateUS</a>
            </th>           
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Active Hrs</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">InActive Hrs</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">BillableInActive Hrs</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Total Hrs</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Productivity</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Productivity %</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Quality</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Quality %</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Average Score</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Final Amount Payable</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Additional Project Allowance</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Status</a>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LookupID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BillingMonth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JoinedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Contract)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
                &nbsp;&nbsp;&nbsp;
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PacteraEdgeEmail)
            </td>            
            <td>
                @Html.DisplayFor(modelItem => item.PayRateUS)
            </td> 
            <td>
                @Html.DisplayFor(modelItem => item.ActiveHrs)
            </td> 
            <td>
                @Html.DisplayFor(modelItem => item.InactiveHrs)
            </td> 
            <td>
                @Html.DisplayFor(modelItem => item.BillableInactiveHrs)
            </td> 
            <td>
                @Html.DisplayFor(modelItem => item.TotalHrs)
            </td> 
            <td>
                @Html.DisplayFor(modelItem => item.Productivity)
            </td> 
            <td>
                @Html.DisplayFor(modelItem => item.ProductivityPercentage)
            </td> 
            <td>
                @Html.DisplayFor(modelItem => item.quality)
            </td> 
            <td>
                @Html.DisplayFor(modelItem => item.qualitypercentage)
            </td> 
            <td>
                @Html.DisplayFor(modelItem => item.averagescore)
            </td> 
            <td>
                @Html.DisplayFor(modelItem => item.finalamountpayable)
            </td> 
            <td>
                @Html.DisplayFor(modelItem => item.USDTotal)
            </td> 
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td> 
                    @if (ViewBag.RoleLevel != null) {
                    <td>
                    <a class="btn btn-info" href="/Sglookup/Edit/@item.LookupID">Edit</a> |
                    <a class="btn btn-info" href="/Sglookup/Delete/@item.LookupID">Delete</a>
                    </td>
                    }
                        else
                        {
                            
                        }  
        </tr>
}
    </tbody>
</table>    
@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
    Next
</a>
</body>
</html>