Controllers/AnnotatorWeeklyController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using MySql.Data.MySqlClient;
using Nancy.Json;
using RoleBasedAuthorization.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RoleBasedAuthorization.Controllers
{
    public class AnnotatorWeeklyController : Controller
    {
        MyDbContext _context = new MyDbContext();
        public static IConfiguration Configuration;

        public AnnotatorWeeklyController(IConfiguration _configuration)
        {
            Configuration = _configuration;
        }
        public IEnumerable<SelectListItem> GetMonth()
        {
             var Provinces = new List<SelectListItem>();
             
                Provinces.Add(new SelectListItem() { Text = "January", Value = "January" });
                Provinces.Add(new SelectListItem() { Text = "February", Value = "February" });
                Provinces.Add(new SelectListItem() { Text = "March", Value = "March" });
                Provinces.Add(new SelectListItem() { Text = "April", Value = "April" });
                Provinces.Add(new SelectListItem() { Text = "May", Value = "May" });
                Provinces.Add(new SelectListItem() { Text = "June", Value = "June" });
                Provinces.Add(new SelectListItem() { Text = "July", Value = "July" });
                Provinces.Add(new SelectListItem() { Text = "August", Value = "August" });
                Provinces.Add(new SelectListItem() { Text = "September", Value = "September" });
                Provinces.Add(new SelectListItem() { Text = "October", Value = "October" });
                Provinces.Add(new SelectListItem() { Text = "November", Value = "November" });
                Provinces.Add(new SelectListItem() { Text = "December", Value = "December" });

           return this.ViewBag.MONTHLY = new SelectList(Provinces, "Value", "Text");

        }

        public List<string> GetMonthList(string month)
        {
            List<string> domains = new List<string>();
            domains.Add("January");
            domains.Add("February");
            domains.Add("March");
            domains.Add("April");
            domains.Add("May");
            return domains;
        }
        public async Task<IActionResult> Index(int? errorId, string otherParam)
        {
            if (HttpContext.Session.GetString("email") == null)
            {
                return Redirect("/Account/Login");
            }
            if (errorId > 0)
            {
                ViewBag.numberofweek = errorId;
                //IEnumerable<SelectListItem> monthly = GetMonth();

                ViewBag.MONTHLY = new SelectList(_context.TblMonths, "MonthId", "Month", otherParam);
            }   
            else
            {
                ViewBag.MONTHLY = new SelectList(_context.TblMonths, "MonthId", "Month");
                //IEnumerable<SelectListItem> monthly = GetMonth();
                //ViewBag.MONTHLY = monthly;
            }
            //List<Admins> admins = db.Admins.ToList();
            //List<MonthlyReviews> monthlyreviews = db.MonthlyReviews.ToList();
            AnnotatorModels annotator = new AnnotatorModels();
            //int num = 7;
            //var admins = db.Admins.Where(s => s.RolesId.Equals(num)).Select(e => new SelectListItem() { Value = e.Id.ToString(), Text = e.FullName }).ToList();
            annotator.Annotators = PopulateAnnotators();


            //ViewData["ddlAnnotators"] = admins;

            return View(annotator);
        }
        private static List<SelectListItem> PopulateAnnotators()
        {
            List<SelectListItem> items = new List<SelectListItem>();
            MySqlConnection conn = null;
            string myConn = Configuration.GetConnectionString("myConn");
            conn = new MySqlConnection(myConn);
            string query = " SELECT distinct id,full_name from admins where roles_id=8";
            using (MySqlCommand cmd = new MySqlCommand(query))
            {
                cmd.Connection = conn;
                conn.Open();
                using (MySqlDataReader sdr = cmd.ExecuteReader())
                {
                    while (sdr.Read())
                    {
                        items.Add(new SelectListItem
                        {
                            Text = sdr["full_name"].ToString(),
                            Value = sdr["id"].ToString()
                        });
                    }
                }
                conn.Close();
            }

            return items;
        }

        [AuthorizedAction]
        public IActionResult Create()
        {

            //ViewBag.userroles = new SelectList(PopulateRole(), "Id", "FullName", 1);

            return View();
        }

        [HttpPost]
        public IActionResult WeeklyResult(AnnotatorModels annotatorModels)
        {
            int noofweek = Convert.ToInt32(Request.Form["Numberofweek"].ToString());
            annotatorModels.Annotators = PopulateAnnotators();

            
                if (noofweek == 1)
                {
                    if (annotatorModels.AnnotatorIds != null)
                    {
                            for (int i = 1; i < 2; i++)
                            {
                                var monthly = Request.Form["Monthly"].ToString();
                                var numberofweek = "Week" + i;
                                var startdate = Request.Form["Startdate_" + i].ToString();
                                var enddate = Request.Form["Enddate_" + i].ToString();

                                MySqlConnection conn = null;
                                string myConn = Configuration.GetConnectionString("myConn");
                                conn = new MySqlConnection(myConn);
                                string query = "insert into monthlyreviews(monthly,numberofweek,startdate,enddate) Values ('" + monthly + "','" + numberofweek + "','" + startdate + "','" + enddate + "'); SELECT LAST_INSERT_ID();";
                                conn.Open();
                                MySqlCommand cmd = new MySqlCommand(query, conn);
                                int id = Convert.ToInt32(cmd.ExecuteScalar());
                                conn.Close();



                                 List<SelectListItem> selectedItems = annotatorModels.Annotators.Where(p => annotatorModels.AnnotatorIds.Contains(int.Parse(p.Value))).ToList();

                                foreach (var selectedItem in selectedItems)
                                {
                                    selectedItem.Selected = true;
                                    var userid = selectedItem.Value;

                                    string query1 = "insert into assignmonthlyreviews(monthlyreviewID,rating,annotatorId,status,monthly) Values ('" + id + "','0','"+ userid + "','Processing','" + monthly + "')";
                                    conn.Open();
                                    MySqlCommand cmd1 = new MySqlCommand(query1, conn);
                                    cmd1.ExecuteNonQuery();
                                    conn.Close();
                            }
                        }
                    }
                    
                }
                else if (noofweek == 2)
                {
                    for (int i = 1; i < 3; i++)
                    {
                        List<SelectListItem> selectedItems = annotatorModels.Annotators.Where(p => annotatorModels.AnnotatorIds.Contains(int.Parse(p.Value))).ToList();
                        var monthly = Request.Form["Monthly"].ToString();
                        var numberofweek = "Week" + i;
                        var startdate = Request.Form["Startdate_" + i].ToString();
                        var enddate = Request.Form["Enddate_" + i].ToString();

                        MySqlConnection conn = null;
                        string myConn = Configuration.GetConnectionString("myConn");
                        conn = new MySqlConnection(myConn);
                        string query = "insert into monthlyreviews(monthly,numberofweek,startdate,enddate) Values ('" + monthly + "','" + numberofweek + "','" + startdate + "','" + enddate + "'); SELECT LAST_INSERT_ID();";
                        conn.Open();
                        MySqlCommand cmd = new MySqlCommand(query, conn);
                        int id = Convert.ToInt32(cmd.ExecuteScalar());
                        conn.Close();

                        foreach (var selectedItem in selectedItems)
                        {
                            selectedItem.Selected = true;
                            var userid = selectedItem.Value;

                            string query1 = "insert into assignmonthlyreviews(monthlyreviewID,rating,annotatorId,status,monthly) Values ('" + id + "','0','" + userid + "','Processing','" + monthly + "')";
                            conn.Open();
                            MySqlCommand cmd1 = new MySqlCommand(query1, conn);
                            cmd1.ExecuteNonQuery();
                            conn.Close();
                        }
                    }
                }
                else if (noofweek == 3)
                {
                for (int i = 1; i < 4; i++)
                {
                    List<SelectListItem> selectedItems = annotatorModels.Annotators.Where(p => annotatorModels.AnnotatorIds.Contains(int.Parse(p.Value))).ToList();
                    var monthly = Request.Form["Monthly"].ToString();
                    var numberofweek = "Week" + i;
                    var startdate = Request.Form["Startdate_" + i].ToString();
                    var enddate = Request.Form["Enddate_" + i].ToString();

Views/AnnotatorWeekly/Create.cshtml
@model RoleBasedAuthorization.Models.MonthlyReviews

@{
    ViewData["Title"] = "Create Annotator";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<html>
<body>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        @ViewData["Title"]
    </h1>
</section>
<!-- Main content -->
<section class="content container-fluid">
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Add New Annotation</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                    @using (Html.BeginForm("WeeklyResult", "AnnotatorWeekly", FormMethod.Post))
                    {
                        <div class="box-body">
                        <div class="form-group">
                            <label for="Monthly">Monthly</label>                           
                            <select asp-for="Monthly" name="Monthly" class="form-control">
                                <option value="January">January</option>
                                <option value="February">February</option>
                                <option value="March">March</option>
                                <option value="April">April</option>
                                <option value="May">May</option>
                                <option value="June">June</option>
                                <option value="July">July</option>
                                <option value="August">August</option>
                                <option value="September">September</option>
                                <option value="October">October</option>
                                <option value="November">November</option>
                                <option value="December">December</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="Numberofweek">Number Of Week</label>
                            <input type="text" class="form-control" id="Numberofweek" name="Numberofweek" placeholder="Enter NumberOfWeek">
                        </div>
                        <div class="box-footer">
                        <button type="submit" class="btn btn-primary" formaction="Generate" onclick="AddTextBox()">Add</button>
                        </div>
                        <div class="form-group">  
                            @Html.ListBox("ddlAnnotators",  (IEnumerable<SelectListItem>) ViewData["ddlAnnotators"], new { size = 40, width = 1000 }))  
                        </div>  
                        
                         <br/>
                        <br/>
                        <div id="TextBoxContainer">
                            <!--Textboxes will be added here -->
                        </div>
                            
                        <div class="form-group">
                            <label for="Startdate">Start Date</label>
                            <input type="text" class="form-control" id="Startdate" name="Startdate" placeholder="Enter Startdate">
                        </div>
                        <div class="form-group">
                            <label for="Enddate">End Date</label>
                            <input type="text" class="form-control" id="Enddate" name="Enddate" placeholder="Enter Enddate">
                        </div>
                        @*<div class="form-group">
                            <label for="AnnotatorId">Annotator</label>
                          @Html.DropDownList("AnnotatorId", (IEnumerable<SelectListItem>)ViewBag.userroles,null, new { @class = "form-control" })
                         </div>*@
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>        
                    }
                    
                
 @section Scripts
    {
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript">
        function GetDynamicTextBox(value) {
            var div = $("<div />");
 
            var textBox = $("<input />").attr("type", "textbox").attr("name", "DynamicTextBox");
            textBox.val(value);
            div.append(textBox);
 
            var button = $("<input />").attr("type", "button").attr("value", "Remove");
            button.attr("onclick", "RemoveTextBox(this)");
            div.append(button);
 
            return div;
        }
        function AddTextBox() {
            var div = GetDynamicTextBox("");
            $("#TextBoxContainer").append(div);
        }
 
        function RemoveTextBox(button) {
            $(button).parent().remove();
        }
 
        $(function () {
            var values = eval('@Html.Raw(ViewBag.Values)');
            if (values != null) {
                $("#TextBoxContainer").html("");
                $(values).each(function () {
                    $("#TextBoxContainer").append(GetDynamicTextBox(this));
                });
            }
        });
    </script>
    @if (ViewBag.Message != null)
    {
        <script type="text/javascript">
            $(function () {
                alert("@ViewBag.Message")
            });
        </script>
    }
    <!-- Bootstrap -->
    <link href="https://code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css" rel="Stylesheet"
    type="text/css" />
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.7.2.min.js"></script>
    <script type="text/javascript" src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>

    <script>
        function getYesterdayDate() {
			  return new Date(new Date().getTime() - 24*60*60*1000);
			}
	function getTomorrowDate() {
	var today = new Date();
	return new Date(new Date().getFullYear()+'-'+(today.getMonth()+1)+'-'+today.getDate());
	}
    $('#txtSelectedDate').datepicker({
                        minDate: getYesterdayDate(),
				        maxDate: getTomorrowDate()
                  });

            $(function () {
                $('#Startdate').datepicker();
                $('#Enddate').datepicker();
                
            });
    </script>
 }
            </div>
        </div>
    </div>
</section>
<!-- get dem fancy typefaces -->
<script type="text/javascript" src="//use.typekit.net/psm0wvc.js"></script>
<script type="text/javascript">try{Typekit.load();}catch(e){}</script>

    <!--===============================================================================================-->
    <script src="~/vendor/jquery/jquery-3.2.1.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/vendor/bootstrap/js/popper.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/vendor/select2/select2.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/js/main.js"></script>
               
    </body>
   </html>

Views/AnnotatorWeekly/Delete.cshtml
@*@model IEnumerable<RoleBasedAuthorization.Models.ViewModel>

@{
    ViewData["Title"] = "Delete Annotator Weekly";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        @ViewData["Title"]
    </h1>
</section>
<!-- Main content -->
<section class="content container-fluid">
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">
            <h3>Are you sure you want to delete this?</h3>
            <div class="box-body">
                    <table id="example2" class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Monthly</th>
                                <th>NumberOfWeek</th>
                                <th>Start Date</th>
                                <th>End Date</th>
                                <th>Rating</th>
                                <th>Status</th>
                                <th>Annotator</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.monthlyreviews.MonthlyreviewID)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.monthlyreviews.Monthly)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.monthlyreviews.Numberofweek)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.monthlyreviews.Startdate)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.monthlyreviews.Enddate)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.monthlyreviews.Rating)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.monthlyreviews.status)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.admins.FullName)
                                </td>
                                <td>
                                    <form method="post" action="/AnnotatorWeekly/DeleteConfirmed">
                                        <input type="hidden" name="id" value="@item.monthlyreviews.MonthlyreviewID" />
                                        <input type="submit" value="Delete" class="btn btn-default" />
                                    </form>
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>*@

Views/AnnotatorWeekly/Index.cshtml
@model RoleBasedAuthorization.Models.AnnotatorModels

@{
    ViewData["Title"] = "Annotator Weekly";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <title>Annotation Information</title>
    <style>
        input[name=SelectedDate] + img {
            position: relative;
            top: 5px;
            left: 2px;
        }
    </style>
    <script type="text/javascript">
    function validateNumber(e) {
            const pattern = /^[0-9]$/;

            return pattern.test(e.key )
        }    
    </script>
</head>
<body>
<!-- Content Header (Page header) -->
<!-- Main content -->
<section class="content container-fluid">
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Add New Annotation</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                    @using (Html.BeginForm("WeeklyResult", "AnnotatorWeekly", FormMethod.Post))
                    {
                        <div class="form-group">
                            <label for="Monthly">Monthly</label>                                          
                            @Html.DropDownList("MONTHLY", (IEnumerable<SelectListItem>)ViewBag.MONTHLY, null, new { @class ="form-control" })

                        </div>
                        <div class="form-group">
                            <label for="Numberofweek">Number Of Week</label>
                            <input type="text" class="form-control" id="Numberofweek" name="Numberofweek" value="@ViewBag.numberofweek" placeholder="Enter NumberOfWeek">
                            <input type="submit" value="Generate" id="btnGenerate" formaction="IndexRecord" class="btn btn-primary"/>
                        </div>
                        @if(ViewBag.numberofweek != null) 
                        {
                            <div name="numberofweek">
                               
                                @for (int i = 1; i <= ViewBag.numberofweek; i++)
                                {
                                    <div class="form-group">
                                        <label for="Startdate">Start Date @i</label>
                                        <input type="text" class="form-control" id="Startdate_@i" name="Startdate_@i" placeholder="Enter Startdate">
                                    </div>
                                    <div class="form-group">
                                        <label for="Enddate">End Date @i</label>
                                        <input type="text" class="form-control" id="Enddate_@i" name="Enddate_@i" placeholder="Enter Enddate">
                                    </div>            
                              
                                }
                            </div> 
                                
                        }
                        else
                        {
                            
                                
                        }
                         
                        <div class="box-body">
                            <div class="form-group">  
                               @Html.ListBoxFor(m => m.AnnotatorIds,  Model.Annotators, new { size = 40, width = 1000 })  
                            </div>  
                            
                        
                        @*<div class="form-group">
                            <label for="AnnotatorId">Annotator</label>
                          @Html.DropDownList("AnnotatorId", (IEnumerable<SelectListItem>)ViewBag.userroles,null, new { @class = "form-control" })
                         </div>*@
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>        
                    }
                    
                
 @section Scripts
    {
        
    <!-- Bootstrap -->
    <link href="https://code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css" rel="Stylesheet"
    type="text/css" />
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.7.2.min.js"></script>
    <script type="text/javascript" src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>

    <script>
        function getYesterdayDate() {
			  return new Date(new Date().getTime() - 24*60*60*1000);
			}
	function getTomorrowDate() {
	var today = new Date();
	return new Date(new Date().getFullYear()+'-'+(today.getMonth()+1)+'-'+today.getDate());
	}
    $('#txtSelectedDate').datepicker({
                        minDate: getYesterdayDate(),
				        maxDate: getTomorrowDate()
                  });

            $(function () { 
                                $('#Startdate_1').datepicker();
                                $('#Enddate_1').datepicker();
                                $('#Startdate_2').datepicker();
                                $('#Enddate_2').datepicker();
                                $('#Startdate_3').datepicker();
                                $('#Enddate_3').datepicker();
                                $('#Startdate_4').datepicker();
                                $('#Enddate_4').datepicker();
                                $('#Startdate_5').datepicker();
                                $('#Enddate_5').datepicker();

                
            });
    </script>
 }
            </div>
        </div>
    </div>
</section>
<!-- get dem fancy typefaces -->
<script type="text/javascript" src="//use.typekit.net/psm0wvc.js"></script>
<script type="text/javascript">try{Typekit.load();}catch(e){}</script>

    <!--===============================================================================================-->
    <script src="~/vendor/jquery/jquery-3.2.1.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/vendor/bootstrap/js/popper.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/vendor/select2/select2.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/js/main.js"></script>
               
    </body>
   </html>