Controllers/LossHRApprovalController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RoleBasedAuthorization.Models;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace RoleBasedAuthorization.Controllers
{
    public class LossHRApprovalController : Controller
    {
        MyDbContext _context = new MyDbContext();

        [AuthorizedAction]

        //public IActionResult Index()
        //{
        //    return View();
        //}

        public async Task<IActionResult> Index(
    string sortOrder,
    string currentFilter,
    string searchString,
    int? pageNumber, int? errorId)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;
            //var temp = from s in _context.sglookup
            //               select new { s.LookupID, s.FirstName, s.LastName, s.JoinedDate };
            var inq = "Processing";
            IQueryable<Offlinehours> students = from s in _context.Offlinehours
                                                  where inq.Contains(s.status)
                                                  select s;
            //select new { s.LookupID, s.FirstName, s.LastName, s.JoinedDate};
            if (!String.IsNullOrEmpty(searchString))
            {
                students = students.Where(s => s.JobID.Contains(searchString)
                                       || s.locale.Contains(searchString)
                                       || s.WorkedHrs.Contains(searchString)
                                       || s.PacteraEdgeEmail.Contains(searchString)
                                       || s.StarshotCrashIsError.Contains(searchString)
                                      );
            }
            switch (sortOrder)
            {
                case "name_desc":
                    students = students.OrderByDescending(s => s.JobID);
                    break;
                case "Date":
                    students = students.OrderBy(s => s.JobID);
                    break;
                case "date_desc":
                    students = students.OrderByDescending(s => s.JobID);
                    break;
                default:
                    students = students.OrderBy(s => s.PacteraEdgeEmail);
                    break;
            }
            int pageSize = 10;
            ViewData["comment"] = errorId;
            if (ViewData["comment"] != null)
            {
                ViewBag.Message = "Comment";
            }
            //return View(await students.AsNoTracking().ToListAsync());

            return View(await PaginatedList<Offlinehours>.CreateAsync(students.AsNoTracking(), pageNumber ?? 1, pageSize));
        }
        [HttpPost, ActionName("OnGetComment")]
        public async Task<IActionResult> OnGetComment()
        {
            int OfflineHrsID = Convert.ToInt32(Request.Form["OfflineHrsID"].ToString());

            var comment = Request.Form["Comment"].ToString();
            if (String.IsNullOrEmpty(comment))
            {
                ViewData["comment"] = OfflineHrsID;
                return RedirectToAction(nameof(Index), new { @errorId = ViewData["comment"] });
            }
            if (OfflineHrsID == 0)
            {
                return NotFound();
            }
            Offlinehours admin = await _context.Offlinehours.Where(s => s.OfflineHrsID == OfflineHrsID).FirstOrDefaultAsync();
            admin.status = "Rejected";
            admin.comments = comment;
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }        
    
    public async Task<IActionResult> OnPostDelete(int id)
    {
        if (id == null)
        {
            return NotFound();
        }
        Offlinehours admin = await _context.Offlinehours.Where(s => s.OfflineHrsID == id).FirstOrDefaultAsync();
        admin.status = "Confirmed";
        await _context.SaveChangesAsync();

        return RedirectToAction(nameof(Index));
    }
    }
}

Views/LossHRApproval/Index.cshtml
@model RoleBasedAuthorization.PaginatedList<RoleBasedAuthorization.Models.Offlinehours>

@{
    ViewData["Title"] = "Listing Function";

    Layout = "~/Views/Shared/_Layout.cshtml";
}
<html>
<head>
    
</head>
<form asp-action="Index" method="get">

    <br/>

    <br/>
    <div class="form-actions no-color">
        <p>
            Find by data: <input type="text" name="SearchString" value="@ViewData["CurrentFilter"]" />
            <input type="submit" value="Search" class="btn btn-default" /> |
            <a asp-action="Index">Back to Full List</a>
        </p>
    </div>
</form>

<table id="example" class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellspacing="0">    
    <br/>
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">ID</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Job Name</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Locale</a>

            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Worked Hours</a>

            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">PacteraEdgeEmail</a>

            </th>
            @*            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">StarshotCrashIsError</a>
                </th>*@
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Type Of Task</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Status</a>
            </th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    
        @foreach (var item in Model) {
            var tm = "#myModal" + item.OfflineHrsID;
            var mid = "myModal" + item.OfflineHrsID;
            <tr>
                <td>
                @Html.DisplayFor(modelItem => item.OfflineHrsID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JobID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.locale)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WorkedHrs)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PacteraEdgeEmail)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.StarshotCrashIsError)
            </td>     *@       
            <td>
                @Html.DisplayFor(modelItem => item.TypeOfTaskID)
            </td>    
             <td>
                @Html.DisplayFor(modelItem => item.status)
            </td>  
            <td>
                @*<a class="btn btn-info" href="/LossHRApproval/Approve/@item.OfflineHrsID">Approve</a> |
                *@
                <a class="btn btn-info" href="~/LossHRApproval/OnPostDelete?id=@item.OfflineHrsID" asp-page-handler="Delete" asp-route-Id="@item.OfflineHrsID" id="approveBtn" class="btn bg-danger mr-1">Approve</a>
                |  
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="@tm">
                    Reject 
                </button>
                            
                <div class="modal fade" id="@mid" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                <h4 class="modal-title" id="myModalLabel">Reject Confirmation</h4>
                            </div>
                            <div class="modal-body">
                                Are you sure want to reject this item?
                            </div>
                            @using (Html.BeginForm("OnGetComment", "LossHRApproval", FormMethod.Post))
                                {
                                    <div style="margin-left:15px;width:30px;">                                
                                        <textarea cols="50" rows="2" id="Comment" name="Comment" placeholder="Leave Comment ..."></textarea>
                                    </div>
                                   
                                
                                    <div class="modal-footer">
                                        <input type="hidden" name="OfflineHrsID" value="@item.OfflineHrsID" />
                                        @*<a href="~/LossHRApproval/?id=@item.OfflineHrsID" asp-page-handler="Delete" asp-route-Id="@item.OfflineHrsID" id="deleteBtn" class="btn bg-danger mr-1">Reject</a>*@
                                          <input type="submit" value="Reject" id="btnSubmit" class="btn btn-primary" onclick="verify()" />
                                          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                    </div>
                                }
                                                    

                        </div>
                    </div>
                </div>
                
            </td>
            <td>
                @if(ViewBag.Message != null) {
                                <script type="text/javascript">
                                    window.onload = function () {
                                        alert("Please enter the Comment!");
                                    };
                                </script>
                            }  
            </td>
        </tr>
    }
    </tbody>
</table>    
@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
    Next
</a>
</html>